server:
  port: 8080
  servlet:
    context-path: /swffsp
    session:
      timeout: 3m

spring:
  #https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
  datasource.druid:
    #druid数据源配置
    url: jdbc:mysql://127.0.0.1:3306/swffsp?characterEncoding=utf8
    username: root
    password: 123456
    #druid连接池配置
    initial-size: 1
    max-active: 20
    min-idle: 1
    max-wait: 60000
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    max-open-prepared-statements: 20 #和上面的等价
    validation-query: select 1 from dual
    validation-query-timeout: 3000
    test-on-borrow: false
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 6000
    min-evictable-idle-time-millis: 300000
    #max-evictable-idle-time-millis:
    filters: stat,wall #配置多个英文逗号分隔

    #druid监控-WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
    web-stat-filter:
      enabled: true  #是否启用StatFilter默认值true
      url-pattern: /*
      exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      session-stat-enable: false
      session-stat-max-count: 1000
      principal-session-name: admin
      principal-cookie-name: admin
      profile-enable: true

    #druid监控-StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
    stat-view-servlet:
      enabled: true  #是否启用StatViewServlet默认值true
      url-pattern: /druid/*
      reset-enable: true
      login-username: admin
      login-password: 123456
      allow: 128.242.127.1
      deny: 128.242.127.2

    # Spring监控配置，说明请参考Druid Github Wiki，配置_Druid和Spring关联监控配置
    # aop-patterns:  # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔

  # Jpa配置
  jpa:
    open-in-view: true
    properties.hibernate.enable_lazy_load_no_trans: true
    database: mysql
    show-sql: true
    #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#日志配置
logging:
  level:
    root: debug
